apiVersion: apps/v1
kind: Deployment
metadata:
  name: jvm-heap-limits-demo-app-v2
  labels:
    app: jvm-heap-limits-demo-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jvm-heap-limits-demo-v2
  template:
    metadata:
      labels:
        app: jvm-heap-limits-demo-v2
    spec:
      containers:
        - name: jvm-heap-limits-demo-v2
          image: jvm-heap-limits-demo-v2
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 250Mi
            limits:
              memory: 500Mi